fix IndexError
When the following conditions are satisfied, nvPY will be raised
IndexError and the housekeeper was stopped.

1. Select the note at bottom of notes list, and delete it.
2. Update an note that satisfy the condition of
   updated_note_index > deleted_note_index.
3. Step 1. and 2. happened almost at the same time.

DETAILS:
`Controller.observer_notes_db_synced_note()` will update notes list.
But `Controller.selected_note_idx` field is not update.  If you delete
the note at the bottom of notes list, `Controller.selected_note_idx`
field are point to out of range.  So the housekeeper will be crashed
by IndexError.  If any errors occurs during housekeeping, the
housekeeper is no longer work because it crashes before set the timer.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/nvpy/lib/python2.7/lib-tk/Tkinter.py", line 1547, in __call__
    return self.func(*args)
  File "/opt/nvpy/lib/python2.7/lib-tk/Tkinter.py", line 596, in callit
    func(*args)
  File "/opt/nvpy/lib/python2.7/site-packages/nvpy-1.0.0-py2.7.egg/nvpy/view.py", line 1547, in handler_housekeeper
    self.notify_observers('keep:house', None)
  File "/opt/nvpy/lib/python2.7/site-packages/nvpy-1.0.0-py2.7.egg/nvpy/utils.py", line 212, in notify_observers
    o(self, evt_type, evt)
  File "/opt/nvpy/lib/python2.7/site-packages/nvpy-1.0.0-py2.7.egg/nvpy/nvpy.py", line 598, in observer_view_keep_house
    nsynced, sync_errors = self.notes_db.sync_to_server_threaded()
  File "/opt/nvpy/lib/python2.7/site-packages/nvpy-1.0.0-py2.7.egg/nvpy/notes_db.py", line 682, in sync_to_server_threaded
    self.notify_observers('synced:note', utils.KeyValueObject(lkey=okey, old_note=old_note))
  File "/opt/nvpy/lib/python2.7/site-packages/nvpy-1.0.0-py2.7.egg/nvpy/utils.py", line 212, in notify_observers
    o(self, evt_type, evt)
  File "/opt/nvpy/lib/python2.7/site-packages/nvpy-1.0.0-py2.7.egg/nvpy/nvpy.py", line 433, in observer_notes_db_synced_note
    selected_note_o = self.notes_list_model.list[self.selected_note_idx]
IndexError: list index out of range
```